[options]
admin_passwd = admin123
db_host = host.docker.internal
db_port = 5432
db_user = odoo19
db_password = odoo19
addons_path = /mnt/extra-addons/accounting_suite,
              /mnt/extra-addons/themes

